version: "3.9"

services:
  app:
    image: index.docker.io/appsmith/appsmith-ce:latest
    restart: always
    environment:
      APPSMITH_SUPERVISOR_USER: ${SUPERVISOR_USER}
      APPSMITH_SUPERVISOR_PASSWORD: ${SUPERVISOR_PASSWORD}
      APPSMITH_CUSTOM_DOMAIN: ${DOMAIN}
      APPSMITH_ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      APPSMITH_ENCRYPTION_SALT: ${ENCRYPTION_SALT}
      APPSMITH_EMAIL_ENABLED: true
      APPSMITH_SMTP_AUTH_ENABLED: true
      APPSMITH_TLS_ENABLED: true
      APPSMITH_EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      APPSMITH_EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      APPSMITH_EMAIL_SERVER_USERNAME: ${EMAIL_SERVER_USERNAME}
      APPSMITH_EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      APPSMITH_EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      APPSMITH_EMAIL_REPLY_TO_ADDRESS: ${EMAIL_REPLY_TO_ADDRESS}
      HTTP_PROXY: http://0.0.0.0:8080
    volumes:
      - ${BASE_VOLUME}/data:/appsmith-stacks
    expose:
      - 80
      - 8080
    networks:
      - internal
      - nginx
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_APP_CPU:-1}
          memory: ${LIMIT_APP_RAM:-1G}
        reservations:
          cpus: "0.2"
          memory: 128M

networks:
  internal:
  nginx:
    external: true
  monitoring:
    external: true
